# This is the composite action:
#   https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

name: Setup pnpm, node.js and install dependencies
description: Setup pnpm and node.js with caching

inputs:
  run-install:
    description: 'Whether to run `pnpm install`'
    required: false
    default: 'true'
  directory:
    description: 'Working directory to run `pnpm install` in'
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0
      with:
        run_install: false

    - name: Setup Node
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version-file: .nvmrc
        cache: 'pnpm'
        cache-dependency-path: pnpm-lock.yaml

    - name: Install dependencies
      if: ${{ inputs.run-install == 'true' }}
      run: pnpm install --frozen-lockfile
      working-directory: ${{ inputs.directory }}
      shell: bash
