query Me {
  me {
    user {
      accountId
      name
      picture
    }
  }
}

mutation MarkAsRead(
  $notificationIDs: [String!]!
  $collabContextRoutingAri: String
) {
  notifications {
    markNotificationsByIdsAsRead(
      ids: $notificationIDs
      collabContextRoutingAri: $collabContextRoutingAri
    )
  }
}

mutation MarkAsUnread(
  $notificationIDs: [String!]!
  $collabContextRoutingAri: String
) {
  notifications {
    markNotificationsByIdsAsUnread(
      ids: $notificationIDs
      collabContextRoutingAri: $collabContextRoutingAri
    )
  }
}

query RetrieveNotificationsByGroupId(
  $groupId: String!
  $first: Int
  $readState: InfluentsNotificationReadState
) {
  notifications {
    notificationGroup(
      groupId: $groupId
      first: $first
      filter: { readStateFilter: $readState }
    ) {
      nodes {
        ...GroupNotificationDetails
      }
    }
  }
}

fragment GroupNotificationDetails on InfluentsNotificationItem {
  notificationId
  readState
}

query MyNotifications(
  $readState: InfluentsNotificationReadState
  $flat: Boolean = true
  $first: Int
  $after: String
  $collabContextRoutingAri: String
) {
  notifications {
    unseenNotificationCount(collabContextRoutingAri: $collabContextRoutingAri)
    notificationFeed(
      flat: $flat
      first: $first
      after: $after
      filter: { readStateFilter: $readState }
      collabContextRoutingAri: $collabContextRoutingAri
    ) {
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
        ...AtlassianNotification
      }
    }
  }
}

fragment AtlassianNotification on InfluentsNotificationHeadItem {
  groupId
  groupSize
  additionalActors {
    displayName
    avatarURL
  }
  headNotification {
    ...AtlassianHeadNotification
  }
}

fragment AtlassianHeadNotification on InfluentsNotificationItem {
  notificationId
  timestamp
  readState
  category
  content {
    type
    message
    url
    #FIXME - For some unknown reason, adding bodyItems fixes
    # - missing notification results for Confluence "shared a page with you" based notifications
    # - populates content.url and entity.url for Confluence "Live Document" based notifications.
    bodyItems {
      appearance
      author {
        actorType
        ari
        avatarURL
        displayName
      }
      document {
        data
        format
      }
    }
    entity {
      title
      iconUrl
      url
    }
    path {
      title
      iconUrl
      url
    }
    actor {
      displayName
      avatarURL
    }
  }
  analyticsAttributes {
    key
    value
  }
}

query RetrieveCloudIDsForHostnames($hostNames: [String!]!) {
  tenantContexts(hostNames: $hostNames) {
    cloudId
    hostName
  }
}
