name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  lint:
    name: Lint App
    uses: ./.github/workflows/lint.yml
    with:
      directory: '.'

  tests:
    name: Tests
    uses: ./.github/workflows/test.yml
    needs: lint
    secrets: inherit

  build:
    name: Build
    uses: ./.github/workflows/build.yml
    needs: tests
    if: ${{ !startsWith(github.head_ref, 'release/v') }}
    secrets: inherit

  release:
    name: Release
    uses: ./.github/workflows/release.yml
    needs: tests
    if: ${{ startsWith(github.head_ref, 'release/v') }}
    secrets: inherit
    permissions: 
      contents: write
