name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
    permissions:
      contents: read
    with:
      directory: "."

  tests:
    name: Tests
    uses: ./.github/workflows/test.yml
    needs: lint
    permissions:
      contents: read
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    name: Build
    uses: ./.github/workflows/build.yml
    needs: tests
    permissions:
      contents: read
    secrets:
      APTABASE_KEY: ${{ secrets.APTABASE_KEY }}
      # Signing certificates
      CSC_LINK: ${{ secrets.CSC_LINK }}
      WIN_CSC_LINK: ${{ secrets.WIN_CSC_LINK }}
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      WIN_CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}
