name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  lint-app:
    uses: ./.github/workflows/lint.yml

  run-unit-tests:
    uses: ./.github/workflows/test.yml
    needs: lint-app
    secrets: inherit

  build-macos:
    name: Build macOS (electron-builder)
    runs-on: macos-latest
    needs: run-unit-tests
    if: ${{ !startsWith(github.head_ref, 'release/v') }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
      - run: pnpm prepare:remove-source-maps
      - run: pnpm package:macos --publish never -c.mac.identity=null
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      - name: Clean up builds
        run: rm -rfv dist/mac-universal
      - uses: actions/upload-artifact@v4
        with:
          name: Atlassify-dist-mac
          path: |
            dist/*
            !dist/**/*.dmg
          overwrite: true

  build-windows:
    name: Build Windows (electron-builder)
    runs-on: windows-latest
    needs: run-unit-tests
    if: ${{ !startsWith(github.head_ref, 'release/v') }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
      - run: pnpm prepare:remove-source-maps
      - run: pnpm package:win --publish never
      - name: Clean up builds
        run: Remove-Item dist/win-unpacked -Recurse
      - uses: actions/upload-artifact@v4
        with:
          name: Atlassify-dist-win
          path: dist/
          overwrite: true

  build-linux:
    name: Build Linux (electron-builder)
    runs-on: ubuntu-latest
    needs: run-unit-tests
    if: ${{ !startsWith(github.head_ref, 'release/v') }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
      - run: pnpm prepare:remove-source-maps
      - run: pnpm package:linux --publish never
      - name: Clean up builds
        run: rm -rfv dist/linux-unpacked
      - uses: actions/upload-artifact@v4
        with:
          name: Atlassify-dist-linux
          path: dist/
          overwrite: true
