name: Lint

on:
  workflow_call:
    inputs:
      directory:
        type: string
        required: true
        description: "The directory to lint"

permissions:
  contents: read

jobs:
  lint:
    name: biomejs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout and setup
        uses: ./.github/actions/setup-node
        with:
          directory: ${{ github.event.inputs.directory }}

      - name: Run linter
        run: pnpm lint:check
        working-directory: ${{ github.event.inputs.directory }}
