name: Add milestone on merge
on:
  pull_request:
    branches:
        - main
    types: 
        - closed

permissions:
  pull-requests: write # for adding milestones to pull requests

jobs:
  add-milestone:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: benelan/milestone-action@ae503769af66e741a9d7f76052058e1c3054fd7e # v3.1.0
        with:
          single: true