name: Website

on:
  workflow_dispatch: # For manually running website deployment

jobs:
  redeploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Redeploy Website
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
