name: Website

on:
  workflow_dispatch: # For manually running website deployment

jobs:
  redeploy-website:
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
